# ============================================================
# application.properties
# Configuración BASE del microservicio.
# Los valores de ambiente específico van en application.dev.yml,
# application.qa.yml, application.prod.yml
# ============================================================

# Nombre de la aplicación (usado en logs y Actuator)
spring.application.name=microservicio-practica

# Ruta base de todos los endpoints de la API
server.servlet.context-path=/api

server.port=8082
